project:
  type: website

website:
  title: "Trinity_Williford"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true


